conda env export -n deepxde-tensorflow > deepxde-tensorflow.yml
conda env export -n dso > dso.yml
conda env export -n ellyn > ellyn.yml
conda env export -n gpg > gpg.yml
conda env export -n py2matlab > py2matlab.yml
conda env export -n py2r > py2r.yml
conda env export -n py3.5 > py35.yml
conda env export -n py3.7 > py37.yml
conda env export -n py3.8 > py38.yml
conda env export -n pydeepxde > pydeepxde.yml
conda env export -n pymc3_env > pymc3_env.yml
conda env export -n pymc_env > pymc_env.yml
conda env export -n pyoperon > pyoperon.yml
conda env export -n pypde-env > pypde-env.yml
conda env export -n pysindy_latest > pysindy_latest.yml
conda env export -n pysr > pysr.yml
conda env export -n pysr_derivative_latest > pysr_derivative_latest.yml
conda env export -n skbayes > skbayes.yml
conda env export -n torch_env > torch_env.yml
conda env export -n trees > trees.yml

